name: Build ROMs

on:
  push:
    branches: [ main, test-github-actions ]
  pull_request:
    branches: [ main, 0.1.6 ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cc65 make vice
      
    - name: Build ROMs
      run: make

    - name: Build PET support images
      run: make support
      
    - name: Upload ROMs and support images
      uses: actions/upload-artifact@v4
      with:
        name: diagnostic-rom
        path: |
          build/*.bin
          build/support/*.prg
          build/support/*.d64
