name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags that start with 'v' (e.g., v1.0, v0.2.3)

permissions:
  contents: write  # This is required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cc65 make
      
      - name: Build ROMs
        run: make
      
      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.TAG }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            *.bin
